// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import * as React from "react";

export const Index: Record<string, any> = {
  "animated-pixel-icon": {
    name: "animated-pixel-icon",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "registry/ui/animated-pixel-icon.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    categories: undefined,
    component: React.lazy(
      () => import("@/registry/ui/animated-pixel-icon.tsx")
    ),
    source: "",
    meta: undefined,
  },
  "animated-pixel-icon-demo": {
    name: "animated-pixel-icon-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["animates-pixel-icon"],
    files: [
      {
        path: "registry/examples/animated-pixel-icon-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    categories: undefined,
    component: React.lazy(
      () => import("@/registry/examples/animated-pixel-icon-demo.tsx")
    ),
    source: "",
    meta: undefined,
  },
};
